### ISSUE TITLE
Help to adjust skin to personal wiki

### ISSUE THREAD

**Issue by kauesena** [StarCitizenTools/mediawiki-skins-Citizen#198]
Hi! Wonderful skin! Thank you very much for developing and making it available. I have been really glad since I've found it. .

I would like help changing a few things in order to use the skin for my personal wiki. I am a total novice to css, less, json etc. I thought I could understand my way through the files in the skin folder but I could not.

The following items are what I would like to achieve.
1. Make the dark mode always enabled (I've read it is not possible to toggle it).
2. Make the logout button in the side panel with the same color as the rest of the menu (the red distracts me a bit when I open the panel).
3. Change the values of the colors of dark mode to be closer to the ones I already use on my editor.
4. Change the style of headings and text (font, size, color etc.).

Are there trivial ways to make such changes? If not, could you give me some guidance as to what should I do. Thank you again very much for creating this skin and thank you in advance for the help. 

(Sorry if my wording is confuse at any point. Brazilian here. Also, I've posted this message in the discussion at the mediawiki.org. I apologize if it is not adequate to submit issues which are not bugs or feature requests.)

**Comment by octfx** [comment]
Hey there to address your points:
1. This will take some time, the skin currently adapts to the color scheme set by the operating system, and defaults to light mode
2. You can add additional CSS by editing the `MediaWiki:Common.css` page
  - To remove the red background from the logout button you would have to past the following css into the page:
```css
body.skinCitizen #p-personal #pt-logout a {
  background-color: inherit;
}

body.skinCitizen #p-personal #pt-logout a:hover,
body.skinCitizen #p-personal #pt-logout a:active,
body.skinCitizen #p-personal #pt-logout a:focus {
    color: #54595d !important;
    background-color: #eaecf0;
}

/** This does currently not work
@media screen and (prefers-color-scheme: dark) {
  body.skinCitizen #p-personal #pt-logout a:hover,
  body.skinCitizen #p-personal #pt-logout a:active,
  body.skinCitizen #p-personal #pt-logout a:focus {
    background-color: #34383f;
    color: #c1c2c5 !important;
  }
}
**/
```
One problem with this is, that the MediaWiki css parser currently does not accept `prefers-color-scheme: dark` media queries, so you'll either have to use the colors used in the light _or_ dark-mode.

3. As stated above, this is currently not possible
4. You can add styles for `h1 - h6` in `MediaWiki:Common.css`

Hope this helps :)
