### ISSUE TITLE
Add Support for Extension:Avatar

### ISSUE THREAD

**Issue by AlanYe-Dev** [StarCitizenTools/mediawiki-skins-Citizen#570]
## The Problem
Currently, this extension's function works fine. However, its CSS does not support Citizen skin.
https://www.mediawiki.org/wiki/Extension:Avatar
## The Solution
Add SkinStyle (Maybe)

## The Alternatives
If a user have uploaded he/her avatar, change the user-icon in the corner of bottom-left to avatar. Also add avatar to edit history, recent edits and user page.

**Comment by alistair3149** [comment]
Do you have a sample page and some examples on how the extension works? I couldn't find much information related to it

**Comment by AlanYe-Dev** [comment]
This extension creates an upload special page and /images/avatars
It also includes some [example CSS/JS](https://github.com/nbdd0121/MW-Avatar/tree/master/example) which enables the website to show user's avatar

**Comment by alistair3149** [comment]
We don't have plans currently to add support for avatar since there are multiple extensions doing that and some of those are very complex. However, the following snippet should work for this extension:

`MediaWiki:Citizen.css`
```css
/* Extension:Avatar */
// Style avatar on header
.citizen-userMenu__avatar {
    width: calc( 100% - var(--space-sm) );
    height: calc( 100% - var(--space-sm) );
    background-size: cover;
    border-radius: 100%;
}

// Hide userAvatar icon when avatar is present
.citizen-userMenu__avatar + .mw-ui-icon-wikimedia-userAvatar {
    display: none;
}
```

`MediaWiki:Citizen.js`
```js
/* Extension:Avatar */
function addAvatarToSiteHeader() {
    const container = document.getElementById( 'citizen-userMenu__buttonCheckbox' );
    const avatarEl = document.createElement( 'div' );
    const avatarUrl = mw.config.get( 'wgScriptPath' ) + '/extensions/Avatar/avatar.php?user=' + mw.user.id();
    avatarEl.classList.add( 'citizen-userMenu__avatar' );
    avatarEl.style.backgroundImage = `url( ${avatarUrl} )`;
    container.prepend( avatarEl );
}

if ( mw.user.isAnon === false ) {
    addAvatarToSiteHeader();
}
```
