### ISSUE TITLE
Section heading fonts are being overridden by DiscussionTools

### ISSUE THREAD

**Issue by kirb** [StarCitizenTools/mediawiki-skins-Citizen#930]
## Describe the Bug
DiscussionTools is overriding the section heading font of DiscussionTools, for some reason. This overrides Citizen’s preferred h2 font config.

[The offending styles are here](https://github.com/wikimedia/mediawiki-extensions-DiscussionTools/blob/3fee4420f643035b1d2afe0e6d34554eae90bff6/modules/dt.init.less#L394-L396)

We worked around this using the following. Don't know if this works as intended with the order the skin’s CSS is loaded, but it does work in [[MediaWiki:Citizen.css]].

```css
.ext-discussiontools-visualenhancements-enabled .ext-discussiontools-init-section > h2 {
	font-family: var(--font-family-base) !important;
	font-weight: var(--font-weight-semibold);
}
```

![image](https://github.com/user-attachments/assets/a8e24e4b-8176-4508-9421-528750cc1b5e)

(`--font-family-base` changed to Comic Sans to emphasise the bug)

## Steps to reproduce the behavior:
Reproducible on https://theapplewiki.com/wiki/The_Apple_Wiki:Community_portal (disable our workaround styles first)

1. Set up a wiki with DiscussionTools
2. Create a discussion, or find an existing one

## Expected Behavior
Font should match a regular h2.

## System
See https://theapplewiki.com/wiki/Special:Version

 - MediaWiki version: 1.41.1
 - Server OS: Ubuntu 24.04
 - Installed extensions and versions: See above
 - PHP version: 8.1.29 (fpm-fcgi)
