### ISSUE TITLE
Wikitable border issues

### ISSUE THREAD

**Issue by kirb** [StarCitizenTools/mediawiki-skins-Citizen#932]
## Describe the Bug
Two border-related bugs:

1. All but first of a wikitable `<caption>`’s children incorrectly have a top border:

![image](https://github.com/user-attachments/assets/d4c4b9ec-28df-4530-89d9-f9276c68ebd9)

[Rule causing this](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/blob/db2983f0e9446e4f325dfb1cf3c84b0e3edf8e0d/resources/skins.citizen.styles/skinning/content.tables.less#L78-L81)

2. `rowspan` on the first `<td>` in a `<tr>` in a `.wikitable--border` causes the left border to be missing on the first item of the next row:

<img alt="image" src="https://github.com/user-attachments/assets/d3c067bf-fc73-4a5a-8d20-4a95c1c2ebf5" height="400">

[Rule causing this](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/blob/db2983f0e9446e4f325dfb1cf3c84b0e3edf8e0d/resources/skins.citizen.styles/skinning/content.tables.less#L114-L121)

We worked around this with the following:

```css
.wikitable tr > * {
	border-left: var(--border-width-base) solid var(--border-color-base);
	border-right: var(--border-width-base) solid var(--border-color-base);
}

.wikitable tr > *:first-child {
	border-left: 0;
}

.wikitable tr > *:last-child {
	border-right: 0;
}
```

However, we use vertical borders on all wikitables. This might work as a replacement for `.wikitable--bordered`, but I’m not certain if this was designed in this way to avoid some specific edge case.

## Steps to reproduce the behavior:
Reproducible on:

1. https://theapplewiki.com/wiki/Template:Navbar#See_also
2. https://theapplewiki.com/wiki/XMM6180#Known_Firmware_Versions (disable our workaround styles first)

<br>

1. Make a table such as:

```mediawiki
{| class="wikitable wikitable--border"
|+ Hello world <span>Foo</span> <span>Bar</span>
| rowspan="2" | Foo
| Bar
| Baz
|-
| Baz
| Foo
|}
```

## Expected Behavior
Borders consistently appear only on cells, in the right places.

## System
See https://theapplewiki.com/wiki/Special:Version

 - MediaWiki version: 1.41.1
 - Server OS: Ubuntu 24.04
 - Installed extensions and versions: See above
 - PHP version: 8.1.29 (fpm-fcgi)
