### ISSUE TITLE
Text on redlink categories unreadable on hover

### ISSUE THREAD

**Issue by kirb** [StarCitizenTools/mediawiki-skins-Citizen#933]
## Describe the Bug
When hovering a catlink that doesn’t exist yet, and is also `:visited`, the foreground and background are the same red color.

We work around this with:

```css
.catlinks li > a.new {
	--color-link-red: var(--color-subtle);
	--color-link-red--hover: var(--color-inverted-primary);
	--color-link-red--active: var(--color-inverted-primary);
}
```

## Steps to reproduce the behavior:
1. Create a page linking to a nonexistent category
2. Click the category
3. Go back to the page
4. Hover on the category link

(Or, apply `:hover:visited` pseudoclasses in devtools)

## Expected Behavior
The link should be readable.

## System
See https://theapplewiki.com/wiki/Special:Version

 - MediaWiki version: 1.41.1
 - Server OS: Ubuntu 24.04
 - Installed extensions and versions: See above
 - PHP version: 8.1.29 (fpm-fcgi)
