### ISSUE TITLE
Disable auto TOC collapsible headers

### ISSUE THREAD

**Issue by keepersdungeon** [StarCitizenTools/mediawiki-skins-Citizen#949]
Hello,
Is there a way to disable the auto TOC collapsible headers by default?
I still wanna have the option for collapse them but not automatically

Thank you!

**Comment by alistair3149** [comment]
Yes it is a planned feature for the next release.

**Comment by keepersdungeon** [comment]
Hello @alistair3149 ,
Is there a way to disable the auto TOC collapsible while u implement this in the theme?
Thanks

**Comment by alistair3149** [comment]
> Is there a way to disable the auto TOC collapsible while u implement this in the theme?

There isn't a way now but you can disable the whole collapse feature through CSS:
```css
/* Hide ToC collapse toggle */
.client-js .citizen-toc .citizen-toc-toggle {
	display: none;
}

/* Remove reserved space for ToC collapse toggle */
.citizen-toc-link:has( + .citizen-toc-toggle ) {
	margin-right: 0;
}

/* Do not collapse ToC children */
.client-js .citizen-toc .citizen-toc-level-1 .citizen-toc-list-item {
	display: block;
}
```
